{"name": "test_a", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_file.py:21: AssumptionFailure\n>>\tpytest.assume(4 == 2)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_file.py:21: AssumptionFailure\nE               >>\tpytest.assume(4 == 2)\nE               AssertionError: assert False\n\n/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/six.py:692: FailedAssumption"}, "start": 1586695335809, "stop": 1586695335811, "uuid": "e7419dd3-dcba-4460-842d-3a3c88c6c5f2", "historyId": "1c4d960ecc729184c7584b56e1f07a28", "testCaseId": "f4a72d59131bb79f50eb8c8f9f1fbdb4", "fullName": "test_file#test_a", "labels": [{"name": "suite", "value": "test_file"}, {"name": "host", "value": "JdeMacBook-Pro.local"}, {"name": "thread", "value": "12305-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_file"}]}