{
  "uid" : "1e879dcf89f8221d",
  "name" : "test_sum",
  "fullName" : "test_file#test_sum",
  "historyId" : "6167e6b6e982eacf32093f335c8b5f5d",
  "time" : {
    "start" : 1586598036449,
    "stop" : 1586598036490,
    "duration" : 41
  },
  "status" : "failed",
  "statusMessage" : "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_file.py:11: AssumptionFailure\n>>\tpytest.assume(4 == 3)\nAssertionError: assert False",
  "statusTrace" : "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_file.py:11: AssumptionFailure\nE               >>\tpytest.assume(4 == 3)\nE               AssertionError: assert False\n\n/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/six.py:692: FailedAssumption",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "suite",
    "value" : "test_file"
  }, {
    "name" : "host",
    "value" : "JdeMacBook-Pro.local"
  }, {
    "name" : "thread",
    "value" : "7422-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_file"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : true,
  "retry" : true,
  "extra" : {
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "1e879dcf89f8221d.json",
  "parameterValues" : [ ]
}